# Generated by Django 5.1.7 on 2025-05-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_customeraddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='article',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='item_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
