# Generated by Django 5.1.7 on 2025-05-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_customeraddress_article_customeraddress_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='item_desc',
            new_name='product_name',
        ),
    ]
