# Generated by Django 5.1.7 on 2025-05-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_item_desc_customeraddress_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='Qty',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
