# Generated by Django 5.1.7 on 2025-05-14 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_customeraddress_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='ref_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='sto_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='store_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
